"""add_validator_hash_to_labs

Revision ID: 0d8d015dff70
Revises: 492b080d4670
Create Date: 2026-06-13 21:51:58.477814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8d015dff70'
down_revision: Union[str, None] = '492b080d4670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('validator_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'validator_hash')
    # ### end Alembic commands ###
