"""add_versioning_to_challenges

Revision ID: 492b080d4670
Revises: 0a8c9ff9ad0b
Create Date: 2026-06-13 17:21:04.139873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492b080d4670'
down_revision: Union[str, None] = '0a8c9ff9ad0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('version', sa.Integer(), nullable=True))
    op.execute("UPDATE labs SET version = 1")
    op.alter_column('labs', 'version', nullable=False)

    op.add_column('modules', sa.Column('version', sa.Integer(), nullable=True))
    op.execute("UPDATE modules SET version = 1")
    op.alter_column('modules', 'version', nullable=False)

    op.add_column('sections', sa.Column('version', sa.Integer(), nullable=True))
    op.execute("UPDATE sections SET version = 1")
    op.alter_column('sections', 'version', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'version')
    op.drop_column('modules', 'version')
    op.drop_column('labs', 'version')
    # ### end Alembic commands ###
